model_params:
  name: 'resnet50'
  in_channels: 3
  pretrained: False
  is_camloss: False
  is_regression: False

data_params:
  name: 'ResnetDataset'
  data_path: "file-class.json"
  train_batch_size: 8
  val_batch_size: 50
  val_size: 50
  test_size: 100
  patch_size: 640,896
  num_workers: 4
  mask: False
  mixup: False

exp_params:
  name: 'Resnetperiment'
  LR: 0.00005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 150
  reload_dataloaders_every_epoch: True

logging_params:
  save_dir: "logs/"
  name: "resnet50"

running_type: 'train'

load_index: 0

version_type: "version_1"
